### ISSUE TITLE
Unable execute the ruby calabash script on iOS 10.0 simulator with Xcode version 8 builded app

### ISSUE THREAD

**Issue by gumasankar** [calabash/run_loop#555] opened 2016-10-13 05:57 UTC
Hello Team, 
We have upgraded our Xcode to version 8 and building the iOS 10.0 version application. While running the calabash scripts on the iOS application, we are getting the below issue,

Expected instruments to report an Automation tracetemplate. 
 Please report this as bug: https://github.com/calabash/run_loop/issues 
 In the bug report, include the output of:

We are using the cucumber-calabash version 0.20.0 and other latest versions of the gems being used, but still we are unable to proceed further. Please help us here.

Please find the complete error log from the terminal we received. 
-------------------------------------------------------------------------- 
Using the ios profile... 
Feature: settings

  @settings1 
  Scenario: Edit dashboard # features/settings.feature:10 
 Expected instruments to report an Automation tracetemplate. 
 Please report this as bug: https://github.com/calabash/run_loop/issues 
 In the bug report, include the output of: 
  
 $ xcrun xcodebuild -version 
 $ xcrun instruments -s templates 
  (RuntimeError) 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop/core.rb:775:in `default_tracetemplate' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop/core.rb:729:in `automation_template' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop/core.rb:310:in `run_with_options' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop.rb:106:in `run' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:767:in `block in new_run_loop' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:765:in `times' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:765:in `new_run_loop' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:635:in `relaunch' 
 /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/platform/features/ios/support/01_launch.rb:27:in `Before' 
    Given I sign in successfully # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:1 
    When I go to Manage dashboards under Settings # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:6 
    And I edit dashboard name # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:35 
    Then I should see the edited dashboard name # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:45 
      undefined method `driver' for nil:NilClass (NoMethodError) 
      /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/platform/features/ios/support/01_launch.rb:40:in `After'

Failing Scenarios: 
cucumber -p ios features/settings.feature:10 # Scenario: Edit dashboard

1 scenario (1 failed) 
4 steps (4 skipped) 
0m2.761s 
Umasankars-MacBook-Pro:platform umasankar$ sh run_ios.sh 
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/autosave_settings_page.rb:19: warning: string literal in condition 
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/autosave_settings_page.rb:23: warning: string literal in condition 
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/autosave_settings_page.rb:30: warning: string literal in condition 
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/bond_repayments_calculator_page .rb:15: warning: string literal in condition 
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/dashboard_page.rb:192: warning: string literal in condition 
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/edit_dashboard_page.rb:115: warning: string literal in condition 
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/explore_page.rb:60: warning: string literal in condition
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/explore_page.rb:67: warning: string literal in condition
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/explore_page.rb:72: warning: string literal in condition
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/explore_page.rb:77: warning: string literal in condition
/Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/ios/pages/explore_page.rb:89: warning: string literal in condition
Using the ios profile... 
Feature: settings

  @settings1 
  Scenario: Edit dashboard # features/settings.feature:10 
 Expected instruments to report an Automation tracetemplate. 
 Please report this as bug: https://github.com/calabash/run_loop/issues 
 In the bug report, include the output of: 
  
 $ xcrun xcodebuild -version 
 $ xcrun instruments -s templates 
  (RuntimeError) 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop/core.rb:775:in `default_tracetemplate' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop/core.rb:729:in `automation_template' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop/core.rb:310:in `run_with_options' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/run_loop-1.5.6/lib/run_loop.rb:106:in `run' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:767:in `block in new_run_loop' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:765:in `times' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:765:in `new_run_loop' 
 /Users/umasankar/.rvm/gems/ruby-2.1.1/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:635:in `relaunch' 
 /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/platform/features/ios/support/01_launch.rb:27:in `Before' 
    Given I sign in successfully # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:1 
    When I go to Manage dashboards under Settings # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:6 
    And I edit dashboard name # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:35 
    Then I should see the edited dashboard name # /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/common/steps/settings.rb:45 
      undefined method `driver' for nil:NilClass (NoMethodError) 
      /Users/umasankar/Documents/WORK/SBG/REGRESSION/SEP22/sbg-mobile-test/platform/features/ios/support/01_launch.rb:40:in `After'

Failing Scenarios: 
cucumber -p ios features/settings.feature:10 # Scenario: Edit dashboard

1 scenario (1 failed) 
4 steps (4 skipped) 
0m5.520s 
Umasankars-MacBook-Pro:platform umasankar$

**Comment by jmoody** [comment] 2016-10-13 09:12
Exact duplicate of **Expected instruments to report an Automation tracetemplate** #552

Please check the closed issues.

Please use GitHub Markdown formatting: specifically "```"

```
gem 'calabash-cucumber', '~> 0.16.3'
Using run_loop 1.5.6
```

Xcode 8 requires Calabash iOS 0.20.0.

In Xcode 8 there is no Automation template - UIAutomation has been removed.

https://github.com/calabash/calabash-ios/wiki/DeviceAgent

**Closed by jmoody** 2016-10-13 09:12 UTC

**Comment by gumasankar** [comment] 2016-10-18 05:20
is there any other solutions to proceed further ?
