### ISSUE TITLE
RunLoop::CoreSimulator.set_timezone 

### ISSUE THREAD

**Issue by perwyl** [calabash/run_loop#619] opened 2017-04-13 07:35 UTC
Can we set the time zone as well? 

Currently we are able to set the language and locale on the simulator. 

```
RunLoop::CoreSimulator.set_language
RunLoop::CoreSimulator.set_locale
```

**Comment by jmoody** [comment] 2017-04-13 08:31
Duplicate of https://github.com/calabash/calabash-ios/issues/1293

**Closed by jmoody** 2017-04-13 08:31 UTC
